name: publish to npm

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      # - name: Install mocha
      #   run: npm install -g mocha
      - name: Install dependencies
        run: npm ci
      # - name: Run tests
      #   run: npm test
      - name: Package and publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
